roles/rsyslog/README.md
roles/rsyslog/defaults/main.yaml
roles/rsyslog/tasks/main.yaml

Add a missing variable rsyslog__capabilities to README.

Make rsyslog__weight_map consistent.

---

roles/rsyslog/README.md
roles/rsyslog/defaults/main.yaml
roles/rsyslog/tasks/main.yaml
roles/rsyslog/templates/etc/rsyslog.conf.j2
roles/rsyslog/templates/etc/rsyslog.d/rules.conf.j2

1. Fixing "DEPRECATION WARNING" from the TASK "Install/Update required packages"
Avoid using loop, devide each package array and assign it to its own task.
(Unfortunately, it made the code uglier...)
2. Defining rsyslog_purge_original_conf to manage pre-existing config files to keep or purge.
3. Adding 'libselinux-python' to rsyslog_base_packages to avoid the installation
failure due to the missing package.  
(Not sure this is the right package to be in the list.)
4. Replacing rsyslog__ with rsyslog_

Updating the rsyslog roles based on the reviews by @sradco

---

roles/rsyslog/README.md
roles/rsyslog/defaults/main.yaml
roles/rsyslog/roles/input_roles/debops/tasks/cleanup.yaml
roles/rsyslog/roles/input_roles/debops/tasks/main.yaml
roles/rsyslog/roles/input_roles/ovirt/defaults/main.yaml
roles/rsyslog/roles/input_roles/ovirt/tasks/cleanup.yaml
roles/rsyslog/roles/input_roles/ovirt/tasks/main.yaml
roles/rsyslog/roles/input_roles/viaq-k8s/tasks/cleanup.yaml
roles/rsyslog/roles/input_roles/viaq-k8s/tasks/main.yaml
roles/rsyslog/roles/input_roles/viaq/defaults/main.yaml
roles/rsyslog/roles/input_roles/viaq/tasks/cleanup.yaml
roles/rsyslog/roles/input_roles/viaq/tasks/main.yaml
roles/rsyslog/roles/output_roles/elasticsearch/defaults/main.yaml
roles/rsyslog/roles/output_roles/elasticsearch/tasks/main.yaml
roles/rsyslog/tasks/main.yaml
tasks/main.yaml

Update ovirt formatting and include_role path so it can
accept prefix of the logging role path.

Update ovirt formatting and include_role path

---

.travis.yml

Update .travis.yml indentation

---

roles/rsyslog/tasks/main.yaml

Update debug message location for clarity

---

roles/rsyslog/roles/input_roles/ovirt/defaults/main.yaml

Updated in the ovirt sub role the
if conditions to use "startswith"
instead of "equal" for collectd records.

Updated oVirt input sub role

---

roles/rsyslog/roles/input_roles/ovirt/defaults/main.yaml

ovirt subrole: Update bug in oVirt logs parsing

---

roles/rsyslog/roles/input_roles/ovirt/defaults/main.yaml

Fixed oVirt logs parsing due to rsyslog bug with prefix

---

molecule/default/molecule.yml

Skip line length verification in ansible-lint

---

README.md

This patch adds details on how other projects can integrate
and add their code to the logging role.
Signed-off-by: Shirly Radco sradco@redhat.com

Update README file with new projects integration details

---

roles/rsyslog/roles/input_roles/ovirt/defaults/main.yaml

Fix bug in oVirt formatting of ovirt.entity field

---

roles/rsyslog/roles/input_roles/ovirt/tasks/main.yaml

Remove libvirt.conf when configuring ovirt

---

roles/rsyslog/roles/input_roles/ovirt/tasks/main.yaml

revert commit 10952d51ef0b0587f546fa7c317f54a73a3c6a66

---

roles/rsyslog/roles/output_roles/elasticsearch/defaults/main.yaml
roles/rsyslog/templates/etc/rsyslog.conf.j2

Update elasticsearch output if conditions

---

README.md
roles/rsyslog/README.md
roles/rsyslog/defaults/main.yaml
roles/rsyslog/handlers/main.yaml
roles/rsyslog/roles/input_roles/basics/defaults/main.yaml
roles/rsyslog/roles/input_roles/basics/tasks/main.yaml
roles/rsyslog/roles/input_roles/ovirt/defaults/main.yaml
roles/rsyslog/roles/input_roles/ovirt/tasks/main.yaml
roles/rsyslog/roles/input_roles/viaq-k8s/defaults/main.yaml
roles/rsyslog/roles/input_roles/viaq/defaults/main.yaml
roles/rsyslog/roles/input_roles/viaq/tasks/main.yaml
roles/rsyslog/roles/output_roles/elasticsearch/defaults/main.yaml
roles/rsyslog/roles/output_roles/elasticsearch/tasks/main.yaml
roles/rsyslog/roles/output_roles/files/defaults/main.yaml
roles/rsyslog/roles/output_roles/forwards/defaults/main.yaml
roles/rsyslog/tasks/cleanup.yaml
roles/rsyslog/tasks/deploy.yaml
roles/rsyslog/tasks/main.yaml
roles/rsyslog/templates/etc/rsyslog.conf.j2
roles/rsyslog/templates/etc/rsyslog.d/rules.conf.j2
tasks/main.yaml
tests/tests_enabled.yml
tests/tests_files.yml
tests/tests_listen.yml

Replacing 'yum' with 'package'.
Removing quotes from single values in the tasks.
Lowering the letter cases of True/False.
White spaces in jinja2: {{ variable_name_here }} and {{ variable_name | default(...) }}

Following Ansible Best Practices

---

.travis.yml
roles/rsyslog/roles/output_roles/files/defaults/main.yml
roles/rsyslog/tasks/main.yml
roles/rsyslog/templates/etc/rsyslog.conf.j2
tests/tests_enabled.yml

Replacing selectattr with json_query in __rsyslog_version retrieval.

Removing unnecessary "length > 0" checks.

---

roles/rsyslog/tasks/main.yml

Description: Create a configuration directory (rsyslog_config_dir) if it does not exist.

Create a configuration directory if it does not exist.

---

roles/rsyslog/roles/input_roles/basics/tasks/cleanup.yml
roles/rsyslog/roles/input_roles/files/tasks/cleanup.yml
roles/rsyslog/roles/input_roles/ovirt/tasks/cleanup.yml
roles/rsyslog/roles/input_roles/viaq-k8s/tasks/cleanup.yml
roles/rsyslog/roles/input_roles/viaq/tasks/cleanup.yml

- replacing '../' with dirname in roles/rsyslog/roles/input_roles/*/tasks/cleanup.yml, as well.

do not use ../ in path when including roles 2

---

tests/tests_combination.yml
tests/tests_combination2.yml
tests/tests_default_files.yml
tests/tests_default_files_log_dir.yml
tests/tests_enabled.yml
tests/tests_files.yml
tests/tests_files_elasticsearch.yml
tests/tests_files_files.yml
tests/tests_files_forwards.yml
tests/tests_files_forwards_implicit.yml
tests/tests_forwards.yml
tests/tests_ovirt_elasticsearch.yml
tests/tests_ovirt_elasticsearch_params.yml
tests/tests_remote_default_remote.yml
tests/tests_remote_remote.yml

See the notes in https://docs.ansible.com/ansible/latest/modules/include_module.html#notes
regarding nonintuitive behavior and possible future deprecation.

Replacing "include:" with "include_tasks" in the test playbooks.

---

tests/tests_combination.yml
tests/tests_combination2.yml
tests/tests_default.yml
tests/tests_default_files.yml
tests/tests_default_files_log_dir.yml
tests/tests_enabled.yml
tests/tests_files.yml
tests/tests_files_elasticsearch.yml
tests/tests_files_files.yml
tests/tests_files_forwards.yml
tests/tests_files_forwards_implicit.yml
tests/tests_forwards.yml
tests/tests_ovirt_elasticsearch.yml
tests/tests_ovirt_elasticsearch_params.yml
tests/tests_remote_default_remote.yml
tests/tests_version.yml

and eliminating it from the rest of the test cases.

Executing "Check rsyslog version" test just in tests_version.yml

---

README.md
defaults/main.yml
design_docs/rsyslog_inputs_outputs_flows.md
roles/rsyslog/README.md
roles/rsyslog/defaults/main.yml
roles/rsyslog/tasks/deploy.yml
roles/rsyslog/tasks/inputs/files/main.yml
roles/rsyslog/tasks/main.yml
roles/rsyslog/tasks/outputs/elasticsearch/main.yml
roles/rsyslog/templates/input_basics.j2
roles/rsyslog/templates/input_ovirt.j2
roles/rsyslog/templates/rsyslog.conf.j2
roles/rsyslog/vars/inputs/files/main.yml
roles/rsyslog/vars/inputs/viaq-k8s/main.yml
roles/rsyslog/vars/inputs/viaq/main.yml
roles/rsyslog/vars/main.yml
tests/tests_combination.yml
tests/tests_combination2.yml
tests/tests_combination_absent.yml
tests/tests_files_elasticsearch.yml
tests/tests_files_elasticsearch_certs_incomplete.yml
tests/tests_files_elasticsearch_use_cert_false_with_keys.yml
tests/tests_files_elasticsearch_use_local_cert.yml
tests/tests_files_elasticsearch_use_local_cert_all.yml
tests/tests_files_elasticsearch_use_local_cert_nokeys.yml
tests/tests_files_files.yml

- files input: rsyslog_input_log_path -> input_log_path
- basic input: rsyslog_imjournal_... -> journal_...
- rsyslog_config_dir -> logging_config_dir

Renaming option key names to more generic ones.

---

COPYING
LICENSE
roles/rsyslog/tasks/deploy.yml
roles/rsyslog/tasks/main.yml
roles/rsyslog/templates/rules.conf.j2
roles/rsyslog/vars/inputs/basics/main.yml
roles/rsyslog/vars/inputs/files/main.yml
roles/rsyslog/vars/inputs/ovirt/main.yml
roles/rsyslog/vars/inputs/remote/main.yml
roles/rsyslog/vars/inputs/viaq-k8s/main.yml
roles/rsyslog/vars/inputs/viaq/main.yml
roles/rsyslog/vars/main.yml
roles/rsyslog/vars/outputs/elasticsearch/main.yml
roles/rsyslog/vars/outputs/files/main.yml
roles/rsyslog/vars/outputs/forwards/main.yml
roles/rsyslog/vars/outputs/remote_files/main.yml

Replacing Apache license with GPL v3; Adding GPL v3 License file COPYING.

Updating the LICENSE text

---

README.md

- Turning each example which was a snippet of playbook to a complete one.
- Fixing unmatched and missing highlighting.

Fixing README.md.

---

README.md
tests/tests_remote_remote.yml

Remote_files option aasync_writing still had "on".

Avoiding 'on' and 'off' for the boolean values. 2

---

ansible.cfg
roles/rsyslog/tasks/main.yml
tests/tests_basics_forwards_cert.yml

- Removing unnecessary skip_ansible_lint tags.
- Replacing include with include_tasks.

Code cleanups

---

roles/rsyslog/tasks/main.yml
tasks/main.yml

Per suggestion by @pcahyna [0], eliminating set_fact and using a block var.
[0] https://github.com/linux-system-roles/logging/pull/156#discussion_r463171620

Bug fix: items in logging_flows.input needs to be checked.

---

README.md
roles/rsyslog/tasks/inputs/remote/main.yml
roles/rsyslog/tasks/main.yml
roles/rsyslog/templates/input_remote.j2
roles/rsyslog/templates/input_remote_module.j2
roles/rsyslog/templates/output_forwards.j2
tests/tests_basics_forwards_cacert.yml
tests/tests_basics_forwards_cert.yml
tests/tests_basics_forwards_cert_missing.yml
tests/tests_server.yml
tests/tests_server_conflict.yml

Changing the key-value pair
pki: tls|none
to
tls: true|false
in the remote input (server) and the forwards output (client).

Changing the key-value pair 'pki: tls|none' to 'tls: true|false'

---

README.md
roles/rsyslog/tasks/inputs/relp/main.yml
roles/rsyslog/tasks/outputs/elasticsearch/main.yml
roles/rsyslog/tasks/outputs/relp/main.yml
roles/rsyslog/tasks/set_certs.yml
roles/rsyslog/templates/input_relp.j2
roles/rsyslog/templates/output_elasticsearch.j2
roles/rsyslog/templates/output_relp.j2
roles/rsyslog/vars/inputs/relp/main.yml
roles/rsyslog/vars/main.yml
roles/rsyslog/vars/outputs/elasticsearch/main.yml
roles/rsyslog/vars/outputs/relp/main.yml
tasks/main.yml
tests/tasks/create_tests_certs.yml
tests/tests_files_elasticsearch_certs_incomplete.yml
tests/tests_files_elasticsearch_use_cert_false_with_keys.yml
tests/tests_files_elasticsearch_use_local_cert.yml
tests/tests_files_elasticsearch_use_local_cert_all.yml
tests/tests_files_elasticsearch_use_local_cert_nokeys.yml
tests/tests_relp_client.yml
tests/tests_relp_server.yml

RHELPLAN-32349 - Add omrelp support to outputs.

RHELPLAN-32454 - Add imrelp support to inputs.

---

.travis/runcollection.sh
.travis/utils.sh
tox.ini

- Adding .travis/runcollection.sh.
- Enabling collection as part of tox/travis tests.

RHELPLAN-56581 - sync collections related changes from template to logging role

---

meta/main.yml

Signed-off-by: Jakub Haruda <jharuda@redhat.com>

meta/main.yml: CI - add support for Fedora 33

---

README.md
roles/rsyslog/templates/output_remote_files.j2
tests/tests_remote.yml

resolves https://github.com/linux-system-roles/logging/issues/208

use FROMHOST instead of HOSTNAME for remote files log file name

---

README.md

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1962374

Keep headers at 4-level max, do minor structural corrections

---

roles/rsyslog/templates/rsyslog.conf.j2
roles/rsyslog/templates/rules.conf.j2
tests/tests_basics_files.yml
tests/tests_basics_forwards.yml
tests/tests_combination.yml

BZ#2006230, BZ#2006231, BZ#2006233

Use {{ ansible_managed | comment }} to fix multi-line ansible_managed

---

roles/rsyslog/defaults/main.yml
roles/rsyslog/tasks/inputs/basics/main.yml
roles/rsyslog/tasks/inputs/files/main.yml
roles/rsyslog/tasks/inputs/ovirt/main.yml
roles/rsyslog/tasks/inputs/relp/main.yml
roles/rsyslog/tasks/inputs/remote/main.yml
roles/rsyslog/tasks/main.yml
roles/rsyslog/tasks/outputs/elasticsearch/main.yml
roles/rsyslog/tasks/outputs/files/main.yml
roles/rsyslog/tasks/outputs/forwards/main.yml
roles/rsyslog/tasks/outputs/relp/main.yml
roles/rsyslog/tasks/outputs/remote_files/main.yml
roles/rsyslog/tasks/set_certs.yml
roles/rsyslog/templates/input_basics.j2
roles/rsyslog/templates/input_basics_rhel7.j2
roles/rsyslog/templates/input_ovirt.j2
roles/rsyslog/templates/input_relp.j2
roles/rsyslog/templates/input_remote.j2
roles/rsyslog/templates/input_remote_module.j2
roles/rsyslog/templates/input_template.j2
roles/rsyslog/templates/output_elasticsearch.j2
roles/rsyslog/templates/output_files.j2
roles/rsyslog/templates/output_forwards.j2
roles/rsyslog/templates/output_relp.j2
roles/rsyslog/templates/output_remote_files.j2
roles/rsyslog/vars/inputs/ovirt/main.yml
tasks/main.yml
tests/tests_files_elasticsearch.yml
tests/tests_ovirt_elasticsearch.yml

- Eliminating unnecessary set_fact tasks in tasks/main.yml and moving
them to the individual input and output.
- Eliminating unnecessary loop for the set_certs tasks.
- Fixing a typo and applying the set_certs changes to tests_ovirt_elasticsearch.yml
and tests_files_elasticsearch.yml.

Performance improvement

---

CHANGELOG.md

[1.11.5] - 2023-01-20
- none
- ansible-lint 6.x fixes (#311)
- cleanup non-inclusive words.
- Add check for non-inclusive language

Version 1.11.5 - CHANGELOG.md [citest skip]

---

CHANGELOG.md

Create changelog update and release for version 1.11.7

docs(changelog): version 1.11.7 [citest skip]

---

CHANGELOG.md

Create changelog update and release for version 1.11.8

docs(changelog): version 1.11.8 [citest skip]

---

CHANGELOG.md

Create changelog update and release for version 1.11.9

docs(changelog): version 1.11.9 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.11.10
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

docs(changelog): version 1.11.10 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.12.0

docs(changelog): version 1.12.0 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.12.1

docs(changelog): version 1.12.1 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.12.2

docs(changelog): version 1.12.2 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.12.3

docs(changelog): version 1.12.3 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.12.4

docs(changelog): version 1.12.4 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.12.5

docs(changelog): version 1.12.5 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.12.6
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

docs(changelog): version 1.12.6 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.12.7
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

docs(changelog): version 1.12.7 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.12.8

docs(changelog): version 1.12.8 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.12.9

docs(changelog): version 1.12.9 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.13.0

docs(changelog): version 1.13.0 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.13.1

docs(changelog): version 1.13.1 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.13.2

docs(changelog): version 1.13.2 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.13.5

docs(changelog): version 1.13.5 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.14.2

docs(changelog): version 1.14.2 [citest skip]
