- defaults/main.yml
- roles/rsyslog/roles/input_roles/debops/tasks/main.yaml
- roles/rsyslog/roles/input_roles/ovirt/defaults/main.yaml
- roles/rsyslog/roles/input_roles/ovirt/tasks/cleanup.yaml
- roles/rsyslog/roles/input_roles/ovirt/tasks/main.yaml
- roles/rsyslog/roles/input_roles/viaq-k8s/defaults/main.yaml
- roles/rsyslog/roles/input_roles/viaq-k8s/tasks/cleanup.yaml
- roles/rsyslog/roles/input_roles/viaq-k8s/tasks/main.yaml
- roles/rsyslog/roles/input_roles/viaq/defaults/main.yaml
- roles/rsyslog/roles/input_roles/viaq/tasks/cleanup.yaml
- roles/rsyslog/roles/input_roles/viaq/tasks/main.yaml
- roles/rsyslog/roles/output_roles/elasticsearch/defaults/main.yaml
- roles/rsyslog/roles/output_roles/elasticsearch/tasks/main.yaml
- roles/rsyslog/tasks/cleanup.yaml
- roles/rsyslog/tasks/deploy.yaml
Updated required oVirt timestamp parsing.
Updated sub-roles default config directory to deploy all configuration files to /etc/rsyslog.d/ directory.
When having the pre sub-role directory, there was a problem with the ordering of the files containing the "$IncludeConfig" statement and caused the files to be run in a different order the expected.
>  Update ovirt role timestamp parsing and sub roles deploy config to /etc/rsyslog.d directory

- roles/rsyslog/roles/input_roles/viaq-k8s/defaults/main.yaml
1) Separating input and the rest from the module type mmk8s.conf.
mmk8s.conf is set to the module type, which filename is 10-mmk8s.conf.
On the other hand, the "imfile" module is loaded in viaq_main.  The
filename is 10-viaq_main.conf which is evaluated after 10-mmk8s.conf.
To ease the confusion, separating the imfile input and the rest and
set it to the "input" type.
2) Replacing rsyslog_log_dir with rsyslog_viaq_log_dir since it fails with
unknown variable.
> Fixing 2 issues in viaq-k8s/defaults/main.yaml

- README.md
- molecule/default/Dockerfile.j2
- molecule/default/INSTALL.rst
- molecule/default/molecule.yml
- molecule/default/playbook.yml
- molecule/default/tests/test_default.py
- molecule/default/yaml-lint.yml
- roles/rsyslog/defaults/main.yaml
- roles/rsyslog/roles/input_roles/debops/defaults/main.yaml
- roles/rsyslog/roles/input_roles/debops/tasks/cleanup.yaml
- roles/rsyslog/roles/input_roles/debops/tasks/main.yaml
- roles/rsyslog/roles/input_roles/ovirt/defaults/main.yaml
- roles/rsyslog/roles/input_roles/viaq-k8s/defaults/main.yaml
- roles/rsyslog/roles/input_roles/viaq-k8s/tasks/cleanup.yaml
- roles/rsyslog/roles/input_roles/viaq-k8s/tasks/main.yaml
- roles/rsyslog/roles/input_roles/viaq/defaults/main.yaml
- roles/rsyslog/roles/output_roles/elasticsearch/defaults/main.yaml
- roles/rsyslog/roles/output_roles/elasticsearch/tasks/main.yaml
- roles/rsyslog/tasks/deploy.yaml
- roles/rsyslog/tasks/main.yaml
- tasks/main.yaml
This adds in-tree tests that utilize molecule to test the logging
role.  We use the molecule's docker driver, which will handle the
provisioning and cleanup of containers to use as the target hosts
when testing the roles.  The tests will use a CentOS 7 container
by default, but other targets can easily be specified when the
tests are launched.
The test playbook that we use for now just tests the logging role
defaults.  We can add additional test scenarios in future patches.
Note that there are a number of lint issues with the current role.
For this initial commit, I have disabled the lint tests that fail
so the tests will progress to actually executing the test playbook.
These lint issues should be cleaned up in future commits, and we
should re-enable those lint tests to catch future …
> Add in-tree tests

- roles/rsyslog/tasks/main.yaml
Add condition for checking Rsyslog version.
The version check is only required for
OpenShift use case.
> Add condition for checking Rsyslog version

- meta/main.yml
- molecule/default/yaml-lint.yml
- roles/rsyslog/roles/output_roles/elasticsearch/defaults/main.yaml
Add meta information for Galaxy
Fix bug in Elasticsearch output when using allowUnsignedCerts variable
Fixes #58 
> Add meta information for Galaxy and fix bug in Elasticsearch output

- roles/rsyslog/roles/input_roles/ovirt/defaults/main.yaml
When moving to Rsyslog we removed the ovirt.entity
field that caused the VMS dashboard and VMs related
visualizations to break.
Adding the field back for backwards compatibility.
Bug-Url: https://bugzilla.redhat.com/1717974
> Add ovirt.entity to ovirt collectd records

- roles/rsyslog/templates/etc/rsyslog.conf.j2
- tasks/main.yaml
Removed the check for rsyslog_default,
So the default configuration will be deployed
unless the user will set the rsyslog_default
variable to false.
If rsyslog_default is set to false the rsyslog.conf
will only include the
$IncludeConfig {{rsyslog_config_dir}}/*.conf line.
> Remove the check for rsyslog_default

- .travis.yml
This works around an issue with ansible and molecule that breaks
our CI.  This issue was recently fixed upstream, but is not yet
available in the packages used during testing.
> Workaround for ansible/molecule#1727

- tasks/main.yaml
This patch reverts #68 since the default rsyslog.conf
can't be used when input sub-roles are defined.
It introduced a regression in oVirt and a proper
handling of system logs should be provided in a new patch.
> Revert commit #68 Remove the check for rsyslog_default

- roles/rsyslog/README.md
- roles/rsyslog/defaults/main.yaml
- roles/rsyslog/roles/README.md
- roles/rsyslog/roles/input_roles/ovirt/defaults/main.yaml
- roles/rsyslog/tasks/main.yaml
Added send_targets_only variable and
40-send-targets-only.conf config file.
The config file contains a filter that will filter
logs with 'send_targets_only' set to 'true'
and discard them after all output targets were processed
and before the default rsyslog.conf rules.
Please review: @pcahyna @nhosoi
> Add send_targets_only variable

- tasks/main.yaml
rsyslog_default is set to true by default.
If default rsyslog.conf should not be used,
this parameter should be set to false explicitly.
> Removed rsyslog_default check and config

- defaults/main.yml
- tasks/main.yaml
- it is redundant: there is ansible_python_version for this
- no other role needs it, so it is doubful that it is actually needed
(the role does not even contain any Python code)
- it is not even properly namespaced
- should not be in defaults: it is not supposed to be set by user
and a fact is not supposed to shadow a default
- a fact is not scoped and will persist in the namespace after the role finishes
- libselinux-python is nothing specific to this role and no other role (except
selinux) installs it - if it is really needed, it should be solved in a common
way
> Remove the use_python3 variable and fact

- README.md
- roles/rsyslog/defaults/main.yaml
- roles/rsyslog/roles/input_roles/basics/defaults/main.yaml
- roles/rsyslog/roles/input_roles/basics/vars/main.yaml
- roles/rsyslog/roles/input_roles/files/defaults/main.yaml
- roles/rsyslog/roles/input_roles/ovirt/defaults/main.yaml
- roles/rsyslog/roles/input_roles/ovirt/tasks/main.yaml
- roles/rsyslog/roles/input_roles/ovirt/vars/main.yaml
- roles/rsyslog/roles/input_roles/viaq-k8s/defaults/main.yaml
- roles/rsyslog/roles/input_roles/viaq-k8s/vars/main.yaml
- roles/rsyslog/roles/input_roles/viaq/defaults/main.yaml
- roles/rsyslog/roles/input_roles/viaq/vars/main.yaml
- roles/rsyslog/roles/output_roles/elasticsearch/vars/main.yaml
- roles/rsyslog/roles/output_roles/files/vars/main.yaml
- roles/rsyslog/roles/output_roles/forwards/vars/main.yaml
- Removing unused rule variables rsyslog_rules, rsyslog_group_rules,
rsyslog_host_rules and rsyslog_dependent_rules from roles/rsyslog/defaults/main.yaml.
- Removing unnecessary default filter for __rsyslog_ovirt_prereq_packages
and __rsyslog_ovirt_packages since they are internal and defined in the vars file.
- Fixing obsolete comments.
> Remove unused rule variables

- README.md
- roles/rsyslog/README.md
- roles/rsyslog/roles/output_roles/elasticsearch/defaults/main.yml
Fixing obsolete default paths in README.md, roles/rsyslog/README.md and roles/rsyslog/roles/output_roles/elasticsearch/defaults/main.yml.
> Fixing obsolete default paths

- roles/rsyslog/tasks/deploy.yml
- roles/rsyslog/tasks/main.yml
Policy:
- Logging role sets permissions only when it generates new dirs/files.
- Configuration Directory - 0755
Configuration files - 0644
- Directory to store file outputs (omfile) - if the directory needs
to be created, the permission is 0700.
Per comments from @jvymazal, I'm proposing to have the above policy in the logging role.
https://github.com/linux-system-roles/logging/pull/95#issuecomment-599932174
But any further discussions would be welcome.  Thanks, in advance.
> Adjusting the dir/file modes to the ones defined in the package.

- .travis.yml
- roles/rsyslog/tasks/main.yml
We can just use the `in` test to see if `rsyslog` is
in `ansible_facts.packages` - we do not have to use
`json_query`.  I believe this also gets rid of the
dependency on `jmespath`
> do not use json_query to test for rsyslog package

- roles/rsyslog/roles/input_roles/basics/tasks/main.yml
- roles/rsyslog/roles/input_roles/files/tasks/main.yml
- roles/rsyslog/roles/input_roles/ovirt/tasks/main.yml
- roles/rsyslog/roles/input_roles/viaq-k8s/tasks/main.yml
- roles/rsyslog/roles/input_roles/viaq/tasks/main.yml
- roles/rsyslog/roles/output_roles/elasticsearch/tasks/main.yml
- roles/rsyslog/roles/output_roles/files/tasks/main.yml
- roles/rsyslog/roles/output_roles/forwards/tasks/main.yml
For some reason, when including parent roles from a sub-role
like this:
```yaml
include_role:
name: "{{ role_path }}/../../../"
tasks_from: deploy.yml
```
and there are handlers to be included and executed from the included
role, ansible thinks the handler tasks are separate, and executes
them separately, leading to a problem that the same handler is
executed multiple times in a row.  Using the role path without
`../` allows ansible to correctly determine that the included
handlers are all the same task, and only executes them once.
> do not use ../ in path when including roles

- roles/rsyslog/roles/input_roles/basics/tasks/cleanup.yml
- roles/rsyslog/roles/input_roles/basics/tasks/main.yml
- roles/rsyslog/roles/input_roles/files/tasks/cleanup.yml
- roles/rsyslog/roles/input_roles/files/tasks/main.yml
- roles/rsyslog/roles/input_roles/ovirt/tasks/cleanup.yml
- roles/rsyslog/roles/input_roles/ovirt/tasks/main.yml
- roles/rsyslog/roles/input_roles/viaq-k8s/tasks/cleanup.yml
- roles/rsyslog/roles/input_roles/viaq-k8s/tasks/main.yml
- roles/rsyslog/roles/input_roles/viaq/tasks/cleanup.yml
- roles/rsyslog/roles/input_roles/viaq/tasks/main.yml
- roles/rsyslog/roles/output_roles/elasticsearch/tasks/main.yml
- roles/rsyslog/roles/output_roles/files/tasks/main.yml
- roles/rsyslog/roles/output_roles/forwards/tasks/main.yml
Comment by @richm:
It is not sufficient to use
include_role:
name: "{{ role_path | dirname | dirname | dirname }}"
because that still introduces some ambiguity in the role lookup.
You must add '/rsyslog' to make it use the rsyslog role.
> do not use ../ in path when including roles 3

- roles/rsyslog/handlers/main.yml
- roles/rsyslog/roles/input_roles/basics/tasks/cleanup.yml
- roles/rsyslog/roles/input_roles/basics/tasks/main.yml
- roles/rsyslog/roles/input_roles/files/tasks/cleanup.yml
- roles/rsyslog/roles/input_roles/files/tasks/main.yml
- roles/rsyslog/roles/input_roles/ovirt/tasks/cleanup.yml
- roles/rsyslog/roles/input_roles/ovirt/tasks/main.yml
- roles/rsyslog/roles/input_roles/viaq-k8s/tasks/cleanup.yml
- roles/rsyslog/roles/input_roles/viaq-k8s/tasks/main.yml
- roles/rsyslog/roles/input_roles/viaq/tasks/cleanup.yml
- roles/rsyslog/roles/input_roles/viaq/tasks/main.yml
- roles/rsyslog/roles/output_roles/elasticsearch/tasks/main.yml
- roles/rsyslog/roles/output_roles/files/tasks/main.yml
- roles/rsyslog/roles/output_roles/forwards/tasks/main.yml
Add a condition to restart rsyslogd handler when __rsyslogd_restarted is false.
Once the handler is executed, it sets __rsyslogd_restarted to true.
Revert "do not use ../ in path when including roles 3"
This reverts commit ff5fd47c8df1f5531e775ee8d98a6fde2bad0cf6.
> Workaround to execute "RUNNING HANDLER" from include_role just once.

- README.md
- defaults/main.yml
- roles/rsyslog/README.md
- roles/rsyslog/defaults/main.yml
- roles/rsyslog/tasks/main.yml
- roles/rsyslog/templates/etc/rsyslog.conf.j2
- roles/rsyslog/vars/inputs/ovirt/main.yml
- roles/rsyslog/vars/inputs/viaq-k8s/main.yml
- roles/rsyslog/vars/outputs/files/main.yml
- tasks/main.yml
- tests/tests_default_files_log_dir.yml
- Variables rsyslog_enabled, rsyslog_purge_original_conf, and rsyslog_system_log_dir are internal variables - set through external variables logging_enabled, logging_purge_confs and logging_system_log_dir, respectively. And the variables are renamed to start with '__'.
- Adding a test case tests_default_files_log_dir.yml
> Instead of using set_fact to set internal variables, use role variables in the main task file

- README.md
- design_docs/rsyslog_inputs_outputs_flows.md
- roles/rsyslog/README.md
- roles/rsyslog/templates/output_files.j2
- roles/rsyslog/templates/output_forwards.j2
- tests/tests_combination.yml
- tests/tests_combination2.yml
- tests/tests_files.yml
- tests/tests_files_files.yml
- tests/tests_files_forwards.yml
Files and forwards output uses a filter
`<facility>.<severity>;<exclude0>;<exclude1>;... <output>`
E.g.,
`*.info;authpriv.none;cron.none    /var/log/messages`
Files and forwards logging_output takes exclude subvariable, which used to be
`exclude: <exclude0>;<exclude1>;...`
but by changing it to
`exclude: ;<exclude0>;<exclude1>;...`
by adding `;` at the first column, `output_{files,forwards}.j2` template could
be simplified as follows.
`{{ files_item.facility | d('*') }}.{{ files_item.severity | d('*') }}{{ files_item.exclude | d() }} {{ files_item.path }}`
> Changing the exclude value from string to list.

- roles/rsyslog/tasks/deploy.yml
- roles/rsyslog/tasks/inputs/basics/main.yml
- roles/rsyslog/tasks/inputs/files/main.yml
- roles/rsyslog/tasks/inputs/ovirt/main.yml
- roles/rsyslog/tasks/inputs/remote/main.yml
- roles/rsyslog/tasks/outputs/elasticsearch/main.yml
- roles/rsyslog/tasks/outputs/files/main.yml
- roles/rsyslog/tasks/outputs/forwards/main.yml
- roles/rsyslog/tasks/outputs/remote_files/main.yml
- tests/tests_combination_absent.yml
When an item in logging_inputs and outputs has an absent state,
(assuming the to-be-generated config file name is XX-filename.conf)
case 1) XX-filename.conf does not exist.
logging role does not generate XX-filename.conf
case 2) XX-filename.conf exists.
logging role deletes XX-filename.conf
Questionable case) XX-filename.conf exists; instead of having the
item with the absent state, delete the item from logging_inputs or
outputs. Then, the existing XX-filename.conf remains untouched.
Adding a test playbook tests_combination_absent.yml
> Making "state: absent" work.

- defaults/main.yml
- roles/rsyslog/README.md
- roles/rsyslog/defaults/main.yml
- roles/rsyslog/tasks/main.yml
- roles/rsyslog/templates/global.j2
- roles/rsyslog/templates/input_remote_module.j2
- roles/rsyslog/vars/main.yml
- roles/rsyslog/vars/outputs/forwards/main.yml
- tests/tests_forwards_cert.yml
- New variables for configuring tls
- logging_pki - Specifying rsyslog encryption library
one of the implementations is allowed none, ptcp, tls, gtls, gnutls
Note: none->ptcp, tls,gtls,gnutls->gtls
Default to ptcp (== no tls)
Note: renaming logging_encryption from the previous PR121.
- logging_pki_files - list of pki files dict
logging_pki_files:
- type: ca_cert | cert | key
src:  location of the file on the local host;
if given, the file is deployed to dest value path.
dest: path to be deployed on the target host;
if given, the path is set to the config file.
Default to /etc/pki/tls/certs/ca.crt for ca_cert
/etc/pki/tls/certs/cert.pem for cert
/etc/pki/tls/private/key.pem for key
Note: the paths are adjusted to the certificate system.
- Variables renamed from starting with rsyslog_ to …
> RHELPLAN-43536 - Support tls for the remote input and forwards output

- README.md
- defaults/main.yml
- design_docs/rsyslog_inputs_outputs_flows.md
- roles/rsyslog/templates/input_basics.j2
- roles/rsyslog/templates/input_remote_module.j2
- roles/rsyslog/templates/output_remote_files.j2
- tests/tests_combination.yml
- tests/tests_combination2.yml
- tests/tests_combination_absent.yml
- tests/tests_remote_remote.yml
Introducing the following parameters.
logging_inputs
- basics
- Share parameters ratelimit_burst, ratelimit_interval between imjournal and imuxsock in the basics input.
- global variables used by the remote inputs
- logging_tcp_threads: Input thread count listening on the tcp port. Default to 1.
- logging_udp_threads: Input thread count listening on the udp port. Default to 1.
- logging_udp_system_time_interval: Interval to get the system time. Effective for udp. Default to 2.
- logging_udp_batch_size: Specifies the maximum number of udp messages. Default to 32.
logging_outputs
- remote_files
- `async_writing`: If set to on, the files are written asynchronously. Default to off.
- `client_count`: Count of client logging system supported this rsyslog server. Default to 10.
- …
> RHELPLAN-32352 - Add performance tuning parameters

- README.md
- design_docs/rsyslog_ovirt_support.md
- roles/rsyslog/templates/output_remote_files.j2
- tests/tests_files_elasticsearch.yml
- tests/tests_files_elasticsearch_certs_incomplete.yml
- tests/tests_files_elasticsearch_use_cert_false_with_keys.yml
- tests/tests_files_elasticsearch_use_local_cert.yml
- tests/tests_files_elasticsearch_use_local_cert_all.yml
- tests/tests_files_elasticsearch_use_local_cert_nokeys.yml
- tests/tests_ovirt_elasticsearch.yml
- tests/tests_ovirt_elasticsearch_params.yml
Rsyslog parameter retryfailures (elasticsearch output) async_writing (remote_files output)
expect on | off. The logging role inherited on | off for the allowed values for the params.
But on | off are not the valid bool in ansible. Thus, replacing the pair with true | false
in docs and tests.
> Avoiding 'on' and 'off' for the boolean values.

- COPYING
- LICENSE
- meta/main.yml
- roles/rsyslog/tasks/deploy.yml
- roles/rsyslog/tasks/main.yml
- roles/rsyslog/templates/rules.conf.j2
- roles/rsyslog/vars/inputs/basics/main.yml
- roles/rsyslog/vars/inputs/files/main.yml
- roles/rsyslog/vars/inputs/ovirt/main.yml
- roles/rsyslog/vars/inputs/remote/main.yml
- roles/rsyslog/vars/inputs/viaq-k8s/main.yml
- roles/rsyslog/vars/inputs/viaq/main.yml
- roles/rsyslog/vars/main.yml
- roles/rsyslog/vars/outputs/elasticsearch/main.yml
- roles/rsyslog/vars/outputs/files/main.yml
- roles/rsyslog/vars/outputs/forwards/main.yml
- roles/rsyslog/vars/outputs/remote_files/main.yml
Some files are licensed under GPLv3. These files have the text
SPDX-License-Identifier: GPLv3
in the file header.  All other files, unless noted, are licensed
under the MIT license.
Adding COPYRIGHT-debops.
> Updating LICENSE:

- roles/rsyslog/tasks/deploy.yml
- roles/rsyslog/tasks/inputs/basics/main.yml
- roles/rsyslog/tasks/inputs/files/main.yml
- roles/rsyslog/tasks/inputs/remote/main.yml
- roles/rsyslog/templates/input_template.j2
- Avoid calling the package module with empty list.
- Eliminating unnecessary loop in the input template.
These changes makes the duration of the typical test (tests_basics_files2) shorter by ~25%.
before
```
real	5m0.877s
user	0m58.480s
sys	0m10.091s
```
after
```
real	3m42.993s
user	0m46.090s
sys	0m8.019s
```
> Fixing performance issues.

- tests/tests_combination.yml
- tests/tests_combination2.yml
- Instead of using copy, use shell to create a test input log file for imfile.
It is needed to have the correct selinux type when the input log file is put
in the directory inotify is watching.
- Making the check code for the processed log more strict.
> Fixing combination test playbooks.

- README.md
- defaults/main.yml
- roles/rsyslog/tasks/main.yml
- roles/rsyslog/tasks/outputs/elasticsearch/main.yml
- roles/rsyslog/templates/global.j2
- roles/rsyslog/templates/output_elasticsearch.j2
- tasks/main.yml
- tests/tests_basics_forwards_cert.yml
- tests/tests_basics_forwards_cert_missing.yml
- tests/tests_files_elasticsearch_certs_incomplete.yml
- tests/tests_files_elasticsearch_use_cert_false_with_keys.yml
- tests/tests_files_elasticsearch_use_local_cert.yml
- tests/tests_files_elasticsearch_use_local_cert_all.yml
- tests/tests_files_elasticsearch_use_local_cert_nokeys.yml
- tests/tests_ovirt_elasticsearch.yml
- tests/tests_ovirt_elasticsearch_params.yml
- Complying with the consistent tls parameter/key names:
```
logging_pki_files:
- ca_cert_src:     ca cert path on the control host
cert_src:        cert path on the control host
private_key_src: key path on the control host
ca_cert:     ca cert path on the managed host
cert:        cert path on the managed host
private_key: key path on the managed host
```
- Updated README.md with better parameter grouping
- In the copy task in tasks/main.yml, which copies the src files to the dest,
added a check whether triplets are given or not.
- Adding a test playbook tests_basics_forwards_cert_missing.yml.
- Put the debug code into a block which is needed by the new test which runs
the second logging role for the recovery from the first failure.
- Complying with the consistent tls parameter/key …
> RHELPLAN-45641 - All system roles should use consistent parameter/key names for TLS parameters

- roles/rsyslog/tasks/inputs/basics/main.yml
- roles/rsyslog/templates/input_basics.j2
- tests/tests_combination.yml
- There should not be multiple basics input. The basics input code is implemented to
skip the second and the rest, if any. There was a mistake in the skipping code.
Instead of using ansible_loop.first, change to sort the loop variables by the type
and check ansible_loop.previtem.
- There were wrong loop variables in templates/input_basics.j2. Replacing "input"
with "item".
Adding the test case to tests_combination.yml.
> 2 Bug fixes in the basics input

- roles/rsyslog/tasks/main.yml
- tests/tests_basics_forwards_cacert.yml
When only ca cert is to be deployed, the condition to copy the ca cert was not satisfied by a typo.
> Bug fix: ca cert w/o cert/key is not deployed

- tasks/main.yml
- tests/tests_basics_files2_missing_flows.yml
If logging_flows.input contains an input which matches none of the logging_input names,
the logging_flows.input is silently ignored. It could cause a misconfiguration.
To prevent it, adding a check if logging_flows.inputs includes an item which is not part
of logging_inputs.
> Bug fix: items in logging_flows.input needs to be checked.

- roles/rsyslog/templates/input_basics_rhel7.j2
$IMJournalStateFile imjournal.state
$imjournalRatelimitBurst "{{ item.ratelimit_burst | d(20000) }}"
$imjournalRatelimitInterval "{{ item.ratelimit_interval | d(600) }}"
$imjournalPersistStateInterval "{{ item.journal_persist_state_interval | d(10) }}")
> Imjournal configuration for RHEL-7 was missing the following directives

- README.md
Use backticks. Otherwise asciidoc conversion aborts on the unquoted asterisk.
> Fix verbatim formatting in markdown

- roles/rsyslog/tasks/inputs/remote/main.yml
- roles/rsyslog/tasks/main.yml
Note: In the jinja2 doc:
true(value) and false(value) are "New in version 2.11."
Plus, `eq` is not supported in Jinja 2.7.2.
> Replacing selectattr('tls', 'true'|'false') with selectattr('tls', '==', true|false)

- README.md
- roles/rsyslog/templates/input_remote.j2
- roles/rsyslog/templates/input_remote_module.j2
In the server configuration (remote input), the description of udp_ports
and tcp_ports was not accurate. Added the followings
- If both are set, udp_ports is used and tcp_ports is dropped.
- If both are not set, "tcp_ports: [514]" is added.
- I.e., udp_ports do not have a default value; tcp_ports do "[514]".
The templates input_remote.j2 and input_remote_module.j2 are updated
based on the description.
> Bug 1861318 - [logging role] cannot setup machine with tls

- tests/set_rsyslog_variables.yml
The logging test playbooks checks the generated rsyslog config file
count first to capture the failure at the early stage. The count
could be influenced by the other applications which put its config
file in /etc/rsyslog.d. The extra count was considered, but it
was not strict enough to reduce the error.
Since the config file name generated by the logging role starts
with '[0-9][0-9]-', thus adding it to the find patterns to make
the generated file count more accurate.
Note: Most additional config file does not start with '[0-9][0-9]-',
but there is an exception 21-cloudinit.conf.
> Fixing the file counting code in the tests.

- tests/tests_basics_files.yml
- tests/tests_basics_files2.yml
- tests/tests_basics_files_forwards.yml
- tests/tests_basics_files_log_dir.yml
- tests/tests_basics_forwards_implicit_files.yml
- tests/tests_combination.yml
- tests/tests_combination2.yml
- tests/tests_imuxsock_files.yml
In the code to check the log message is successfully logged or not in the /var/log/messages file, adding "until: __result.rc == 0" and waiting up to 5 seconds.
> Test playbooks - Adding 1 second pause between the logger and its result checking.

- roles/rsyslog/templates/output_elasticsearch.j2
- tests/tests_files_elasticsearch_use_local_cert.yml
When evaluated, the retryfailures value was denied by "not", which
should not have been. Removing the "not" and adding a test case to
tests_files_elasticsearch_use_local_cert.yml.
> Fixing a logic bug in elasticsearch output template.

- tests/tasks/create_tests_certs.yml
To create key and certs on CentOS-7, python2-cryptography needs to
be installed.
> Fixing CI tests using tests/tasks/create_tests_certs.yml

- .ansible-lint
- .github/workflows/tox.yml
- molecule/default/molecule.yml
Deprecate the use of molecule for linting.  Use tox for ansible-lint.
The next step will be to remove the ansible-lint dependency from
the molecule environments.
> use tox for ansible-lint instead of molecule

- README.md
Recovering the oVirt options section in README.md.
> [README] Support oVirt input + elasticsearch output

- molecule/default/molecule.yml
ansible 2.7 has been deprecated
https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html
We need to remove ansible 2.7 from molecule testing in order to
* make room for ansible 2.10 testing
* move to molecule v3
ansible 2.8 and later support platform-python on el8 and later
so we don't have to handle that case explicitly by setting
ansible_python_interpreter for centos8 in molecule.yml
> remove ansible 2.7 support from molecule

- roles/rsyslog/tasks/inputs/remote/main.yml
- roles/rsyslog/tasks/main.yml
- roles/rsyslog/templates/global.j2
- roles/rsyslog/vars/inputs/ovirt/main.yml
- tasks/main.yml
- tests/tests_basics_files.yml
Do not use the case_sensitive argument to the unique filter
For doing selectattr with string comparison, use `match` with
an argument like `^STRING$` instead of `==` or `equalto` with
`STRING`.
For doing selectattr with boolean values, you don't need to
provide a test - `selectattr('boolvar')` is the same as
`selectattr('boolvar', '==', true)`.  For `false` comparison,
use `rejectattr('boolvar')` which is the same as
selectattr('boolvar', '==', false)`
Do not use `namespace` as it is only needed with loops, not `if`
> support jinja 2.7

- README.md
- roles/rsyslog/templates/input_relp.j2
- roles/rsyslog/templates/output_relp.j2
- tasks/main.yml
- tests/tests_relp.yml
This PR contains 2 commits:
1) Bug fix in relp_input - an unwanted loop index was added as suffix
There was a bug in roles/rsyslog/templates/input_relp.j2, in which
$inputname was compared with a name with extra _{{ loop.index }} to
determine the output. It made the relp input never delivered to the
output.
Test case is added to TEST CASE 0 in tests_relp.yml.
2) Bug fix in relp_output - there was inconsistencies in the parameters.
To specify the server host and server port, relp required "server_host"
and "server_port", while the forwards output does "target" and "port".
To eliminate the inconsistency, adjusting the relp parameters to the
forwards output's parameters.
Test case is added to TEST CASE 1 in tests_relp.yml.
> Bug fixes in relp_input and relp_output

- README.md
- roles/rsyslog/templates/input_ovirt.j2
- roles/rsyslog/templates/input_relp.j2
- roles/rsyslog/templates/input_remote.j2
- roles/rsyslog/templates/input_template.j2
- tests/tests_ovirt_elasticsearch.yml
README - Removing a duplicated "port" in the relp output parameter.
- It was introduce in the previous commit cc9af13e7560f975279771c99c8acae7766435f9
Fixing whitespace inconsistencies in the templates.
- input_ovirt.j2,tests_ovirt_elasticsearch.yml - removing an extra whitespace between 'input' and '('.
- input_relp.j2,input_remote.j2,input_template.j2 - removing an extra whitespace before ')'.
> Bug fixes found or introduced in the previous commit "Bug fix in relp_output - there was inconsistencies in the parameters."

- README.md
- roles/rsyslog/tasks/set_certs.yml
- roles/rsyslog/templates/input_relp.j2
- roles/rsyslog/templates/output_elasticsearch.j2
- roles/rsyslog/templates/output_relp.j2
- tests/tests_files_elasticsearch.yml
- tests/tests_relp.yml
When ca_cert_src, cert_src, and private_key_src are specified without the
corresponding target locations ca_cert, cert, and private_key, the files
are copied to /etc/rsyslog.d for the elasticsearch output and the relp
input/output. On the other hand, logging_pki_files copies to /etc/pki/tls.
The inconsistent behaviour should confuse the users. Since relp is new,
and we are releasing the next version as a major update (with major_version++),
it is a good timing to adjust it.
README and test cases are updated.
https://github.com/linux-system-roles/logging/issues/205
> Issue: cert and key files should be deployed in the /etc/pki/tls folder

- roles/rsyslog/templates/input_relp.j2
- roles/rsyslog/templates/output_relp.j2
- tests/tests_relp.yml
There were logic bugs in input_relp.j2 and output_relp.j2 to set default values.
The bugs are fixed and the test cases are added to tests_relp.yml.
> Fixing bugs in permitted_servers and permitted_clients parameter in relp.

- meta/main.yml
- roles/rsyslog/meta/main.yml
From now the `rhel-8-y` status is the latest unreleased RHEL-8 and the `rhel-x` status is pre-released RHEL-9.
> CI: Add support for RHEL-9

- README.md
As suggested, removed numbering and itemizing.
RHELPLAN-80116
> Fixing "logging README.html examples are rendered incorrectly"

- README.md
Options are rendered incorrectly, as well
Instead of using the nested itemize, use headers as h5, h6 are supported by kramdoc.
No wording changes. Modified just markdown codes.
RHELPLAN-80116
> Fixing "logging README.html is rendered incorrectly"

- roles/rsyslog/tasks/main.yml
- tests/tests_basics_files.yml
Note: having the module 'archive' makes the logging role fail with
an error "couldn't resolve module/action 'archive'." if executed
with ansible-navigator.
Stop using set_fact to set rsyslog_backup_dir in roles/rsyslog/tasks/main.yml
to fix a bug that the backup dir could have repeated
rsyslog.d-{{ ansible_date_time.iso8601_basic_short }}
sub-directories if the logging role is executed multiple times.
Move "logging_purge_confs: true" to TEST CASE 3 in tests_basic_files.yml.
> Instead of the archive module, use "tar" command for backup.

- README.md
- roles/rsyslog/templates/output_elasticsearch.j2
- tests/tests_ovirt_elasticsearch.yml
RFE from oVirt:
elasticsearch now allows the server to be a list of servers:
https://www.rsyslog.com/doc/v8-stable/configuration/modules/omelasticsearch.html#server
Is this variable adjusted in Logging repo to be an array?
- `server_host`: Host name Elasticsearch is running on. The value
is a single host or list of hosts. **Required**.
> Add a support for list value to server_host in the elasticsearch output

- tests/tasks/create_tests_certs.yml
Use `python-cryptography` on EL7 - use `python-cryptography3` everywhere
else
https://bugzilla.redhat.com/show_bug.cgi?id=1989962
> use correct python-cryptography package

- README.md
inside role rsyslog `logging_purge_original_conf` variable is named `logging_purge_confs`
> [FIX] README false variable name

- roles/rsyslog/templates/output_elasticsearch.j2
- tests/tests_ovirt_elasticsearch.yml
On python2 (el7) when server_host is a list, this:
```
server={{ item.server_host }}
```
gets rendered as this:
```
server=[u'logging-es0', u'logging-es1']
```
I think we should not rely on the python/jinja2 list to string
conversion being exactly the same format as the rsyslog string list format.
> python2 renders server_host list incorrectly

- roles/rsyslog/tasks/main.yml
https://bugzilla.redhat.com/show_bug.cgi?id=1984182
Use the `args.warn: false` to omit the warning about using
`unarchive` instead of the `tar` command.
Use the `tar` `-P` flag to omit the warning about trimming
leading slashes `/` from the paths.
> do not warn about unarchive or leading slashes

- .github/workflows/tox.yml
- ansible_pytest_extra_requirements.txt
- meta/main.yml
- roles/rsyslog/meta/main.yml
Bug 1989197 - drop support for Ansible 2.8
https://bugzilla.redhat.com/show_bug.cgi?id=1989197
> Drop support for Ansible 2.8 by bumping the Ansible version to 2.9

- tests/tests_basics_files.yml
- tests/tests_basics_forwards.yml
- tests/tests_combination.yml
- tests/tests_default.yml
- tests/tests_enabled.yml
- tests/tests_files_elasticsearch.yml
- tests/tests_files_files.yml
- tests/tests_imuxsock_files.yml
- tests/tests_ovirt_elasticsearch.yml
- tests/tests_relp.yml
- tests/tests_remote.yml
- tests/tests_version.yml
- Removing "become: true" from test scripts.
- Fixed the expected value of the test_relp tls.permittedpeer value.
Ref: 93313
> baseosci - fix logging tests

- roles/rsyslog/tasks/set_certs.yml
Playbook fails when certificates are not used.
This patch adds condition for the copy tasks to perform only when tls is set to true.
Bug-Url: https://bugzilla.redhat.com/1994580
> Update copy tasks conditions with tls true

- roles/rsyslog/tasks/set_certs.yml
- tests/tests_files_elasticsearch.yml
- The case used to fail in the checking task with emitting an error.
The error is transformed to a warning.
- For the test case, TEST CASE 2 in tests_files_elasticsearch.yml
is added.
In addition, some minor bugs in tests_files_elasticsearch.yml are
fixed.
ref: bz1994580
> Allowing the case, tls is false and key/certs vars are configured.

- README.md
- defaults/main.yml
- roles/rsyslog/tasks/deploy_nolog.yml
- roles/rsyslog/tasks/outputs/elasticsearch/main.yml
- roles/rsyslog/templates/output_elasticsearch.j2
- tests/tests_ovirt_elasticsearch.yml
We want to expose the uid and pwd parameters in our role,
to allow basic auth on the elasticsearch server.
The metrics update can be seen here: https://gerrit.ovirt.org/#/c/ovirt-engine-metrics/+/116098/
Bug-Url: https://bugzilla.redhat.com/1990490
Signed-off-by: Aviv Litman <alitman@redhat.com>
> Add uid and pwd parameters

- roles/rsyslog/tasks/inputs/ovirt/main.yml
- roles/rsyslog/vars/inputs/ovirt/CentOS_7.yml
- roles/rsyslog/vars/inputs/ovirt/RedHat_7.yml
- roles/rsyslog/vars/inputs/ovirt/default.yml
- roles/rsyslog/vars/inputs/ovirt/main.yml
In the replacement, a serous redundancy was found in the sub-role
handling. This commit eliminated the extra loop on the ovirt input.
Other inputs and outputs share the same redundancy. They are going
to be cleaned up in a separate commit.
> Replacing seport module with the semanage command line.

- tests/tasks/create_tests_certs.yml
- tests/tests_relp.yml
- tests/tests_server.yml
in the test helper task tests/tasks/create_tests_certs.yml.
This is to avoid using the non ansible-core module.
> Use the openssl command-line interface instead of the openssl module

- README.md
- defaults/main.yml
- roles/rsyslog/tasks/main.yml
- tasks/main.yml
- tests/tests_basics_files.yml
When `logging_purge_confs` is set to `true` and the configuration is cleaned up at the end of the test (e.g., tests_basics_files.yml), the rsyslog configuration on the target nodes are destroyed and rsyslog service fails to restart as shown in this ansible.log.
https://dl.fedoraproject.org/pub/alt/linuxsystemroles/logs/linux-system-roles-logging-pull-linux-system-roles_logging-240-618f22e-rhel-8-y-20220105-174527/artifacts/ansible.log
To mitigate the issue, I'd like to propose to add `logging_restore_confs` variable to restore the conf files from backup if it is set to `true`. In the addition, I'm switching the default backup location from /tmp to /var/tmp to keep the backup in a bit safer place.
> Add logging_restore_confs variable to restore backup.

- tests/tests_enabled.yml
This is part of the effort to allow CI tests run in the serialized
manner on one VM for shortening the duration of the CI tests. The
test case tests_enabled.yml expects the rsyslog configuration file
in the original state from the rsyslog rpm package.
> Initialize tests_enabled.yml by setting "logging_purge_confs: true"

- README.md
- defaults/main.yml
- roles/rsyslog/defaults/main.yml
- roles/rsyslog/tasks/inputs/files/main.yml
- roles/rsyslog/templates/input_files.j2
- roles/rsyslog/templates/output_forwards.j2
- roles/rsyslog/vars/outputs/files/main.yml
- roles/rsyslog/vars/outputs/forwards/main.yml
- tests/tests_basics_files.yml
- tests/tests_basics_forwards.yml
- tests/tests_combination.yml
- tests/tests_files_files.yml
RFE - support template, severity and facility options
- template options to the files & formats output
- severity and facility options to the files input
(issue #271)
Playbook example
```
- name: "Ensure that the role runs with parameters from files input to forwards outputs"
hosts: all
tasks:
- name: "Ensure that the role runs with parameters
from files input to forwards outputs"
vars:
logging_outputs:
- name: forwardToLogServer
type: forwards
target: psyslog.example.com
udp_port: 514
template: RSYSLOG_SyslogProtocol23Format
logging_inputs:
- name: "php:"
type: files
input_log_path: /var/log/php_errors.log
severity: err
logging_flows:
- name: flow
inputs:
- "php:"
outputs:
- forwardToLogServer
include_role:
name: linux-system-roles.logging
```
Generated rsyslog config file example
``` …
```
> RFE - support template, severity and facility options

- roles/rsyslog/tasks/set_vars.yml
`['{{ role_path }}/vars/main.yml']` in the original code fails with `Could not find or access '{{ role_path }}/vars/main.yml'`.
The path in the name string was fixed, as well.
Complete failed message:
```
"message": "Could not find or access '{{ role_path }}/vars/main.yml'
Searched in:
/usr/share/ansible/roles/rhel-system-roles.logging/roles/rsyslog/vars/{{ role_path }}/vars/main.yml
/usr/share/ansible/roles/rhel-system-roles.logging/roles/rsyslog/{{ role_path }}/vars/main.yml
/usr/share/ansible/roles/rhel-system-roles.logging/vars/{{ role_path }}/vars/main.yml
/usr/share/ansible/roles/rhel-system-roles.logging/{{ role_path }}/vars/main.yml
/usr/share/ansible/roles/rhel-system-roles.logging/roles/rsyslog/tasks/vars/{{ role_path }}/vars/main.yml …
```
> Fix including a var file in set_vars.yml.

- roles/rsyslog/tasks/inputs/remote/main.yml
- roles/rsyslog/tasks/main_core.yml
- tasks/main.yml
- tests/setup-snapshot.yml
Looks like ansible-core-2.13 (or latest jinja3) does not support
constructs like this:
```
var: "{{ [some list] }} + {{ [other list] }}"
```
instead, the entire thing has to be evaluated in the same jinja
evaluation context:
```
var: "{{ [some list] + [other list] }}"
```
> support ansible-core-2.13

- CHANGELOG.md
[1.9.4] - 2022-07-19
- none
- support ansible-core-2.13
Looks like ansible-core-2.13 (or latest jinja3) does not support
constructs like this:
```
var: "{{ [some list] }} + {{ [other list] }}"
```
instead, the entire thing has to be evaluated in the same jinja
evaluation context:
```
var: "{{ [some list] + [other list] }}"
```
- use gather_facts: true in tests_include_vars_from_parent
This test does not work with ANSIBLE_GATHERING=explicit - add
explicit gather_facts: true
- make min_ansible_version a string in meta/main.yml
The Ansible developers say that `min_ansible_version` in meta/main.yml
must be a `string` value like `"2.9"`, not a `float` value like `2.9`.
- Add CHANGELOG.md
- Modify CHANGELOG.md
- Replace the ATX style with the setext style for the header H1 …
> Version 1.9.4 - CHANGELOG.md [citest skip]

- README.md
- roles/rsyslog/templates/input_files.j2
- tests/tests_combination.yml
Adds startmsg_regex and endmsg_regex options:
`startmsg_regex`: The regular expression that matches the start part of a message.
`endmsg_regex`: The regular expression that matches the last part of a message.
A test case specifying `endmsg_regex` is added to tests_combination.yml.
> Support startmsg.regex and endmsg.regex in the files inputs.

- CHANGELOG.md
[1.10.0] - 2022-07-28
- Support startmsg.regex and endmsg.regex in the files inputs.
Adds startmsg_regex and endmsg_regex options:
`startmsg_regex`: The regular expression that matches the start part of a message.
`endmsg_regex`: The regular expression that matches the last part of a message.
- none
- Fix a bash bug in changelog_to_tag.yml, which unexpectedly expanded "*"
- changelog_to_tag action - support other than "master" for the main branch name, as well
- Use GITHUB_REF_NAME as name of push branch; fix error in branch detection [citest skip]
We need to get the name of the branch to which CHANGELOG.md was pushed.
For now, it looks as though `GITHUB_REF_NAME` is that name.  But don't
trust it - first, check that it is `main` or `master`.  If not, then use
a …
> Version 1.10.0 - CHANGELOG.md [citest skip]

- tests/tests_basics_forwards.yml
- tests/tests_files_elasticsearch.yml
To avoid the CI conflicts on the control host when running tests in parallel, create a temporary directory by tempfile to store files used in the test.
> Create tempdir to avoid conflicts in the CI

- CHANGELOG.md
[1.11.0] - 2022-11-01
- Use the firewall role, the selinux role, and the certificate role from the logging role (#293)
- Introduce logging_manage_firewall to use the firewall role to manage
the syslog ports. logging_manage_firewall is set to true, by default.
If the variable is set to false, the firewall configuration is
disabled.
- Introduce logging_manage_selinux to use the selinux role to manage
the ports specified in the logging configuration. logging_manage_
selinux is set to true, by default.  If the variable is set to false,
the selinux configuration is disabled except the ports defined in the
selinux policy.
- Add the test check task check_firewall_selinux.yml for verify the
ports status.
- Use the certificate role to generate certificates in the logging role …
> Version 1.11.0 - CHANGELOG.md [citest skip]

- CHANGELOG.md
[1.11.1] - 2022-11-14
- none
- none
- support ansible-core 2.14, ansible-lint 6.x (#297)
The main issue was getting rid of `warn: false` for the
`command` module.  The other issues are related to ansible-lint 6.x
> Version 1.11.1 - CHANGELOG.md [citest skip]

- tests/tasks/test_logger.yml
- tests/tests_relp.yml
- tests/tests_server.yml
Need to use `getcert stop-tracking` when removing the cert, otherwise,
subsequent requests will hang if certmonger is tracking a non-existent
cert.
> cert cleanup needs to use getcert stop-tracking

- CHANGELOG.md
[1.11.2] - 2022-11-19
- none
- cert cleanup needs to use getcert stop-tracking (#300)
Need to use `getcert stop-tracking` when removing the cert, otherwise,
subsequent requests will hang if certmonger is tracking a non-existent
cert.
- increase test log timeout; show log if failed
> Version 1.11.2 - CHANGELOG.md [citest skip]

- tests/tests_relp.yml
On some platforms, there are no packages that put config files in
/etc/rsyslog.d - using `logging_enabled: false` after a test leaves
no files in /etc/rsyslog.d and the `$IncludeConfig /etc/rsyslog.d/*.conf`
then leaves rsyslogd in a state that it will not start and cause test
failures.
The solution is to use `logging_purge_confs: true` which "does the right
thing" when /etc/rsyslog.d is empty.
Fix the expected number of config files check.
> use logging_purge_confs in relp test

- CHANGELOG.md
[1.11.3] - 2022-12-05
- none
- use logging_purge_confs in relp test (#303)
On some platforms, there are no packages that put config files in
/etc/rsyslog.d - using `logging_enabled: false` after a test leaves
no files in /etc/rsyslog.d and the `$IncludeConfig /etc/rsyslog.d/*.conf`
then leaves rsyslogd in a state that it will not start and cause test
failures.
The solution is to use `logging_purge_confs: true` which "does the right
thing" when /etc/rsyslog.d is empty.
Fix the expected number of config files check.
- none
> Version 1.11.3 - CHANGELOG.md [citest skip]

- tests/tests_basics_files.yml
- tests/tests_basics_forwards.yml
- tests/tests_combination.yml
- tests/tests_files_elasticsearch.yml
- tests/tests_files_files.yml
- tests/tests_imuxsock_files.yml
- tests/tests_ovirt_elasticsearch.yml
- tests/tests_relp.yml
- tests/tests_remote.yml
- tests/tests_server.yml
If there are any leftover defined variables that specify inputs, outputs, or flows,
purge will not remove those files since they are referred to.  This typically
happens when using `public: true` which leaves all of those role variables
defined in the public namespace.  The solution when cleaning up is to ensure
that none of the inputs, outputs, or flows is defined when using purge, to
guarantee that all of the config files are removed and none are leftover.
> specify empty inputs, outputs, flows with purge

- CHANGELOG.md
[1.11.4] - 2022-12-13
- none
- tests: specify empty inputs, outputs, flows with purge (#308)
If there are any leftover defined variables that specify inputs, outputs, or flows,
purge will not remove those files since they are referred to.  This typically
happens when using `public: true` which leaves all of those role variables
defined in the public namespace.  The solution when cleaning up is to ensure
that none of the inputs, outputs, or flows is defined when using purge, to
guarantee that all of the config files are removed and none are leftover.
- none
> Version 1.11.4 - CHANGELOG.md [citest skip]

- roles/rsyslog/tasks/inputs/ovirt/main.yml
- tests/tasks/check_daemon_config_files.yml
- tests/tests_basics_files.yml
- tests/tests_basics_forwards.yml
- tests/tests_combination.yml
ansible-lint now requires the use of changed_when even for tasks
that are conditional
> ansible-lint - use changed_when even for tasks with conditionals

- README.md
For roles that use other system roles, they have a
`meta/collection-requirements.yml` file, and the README lists
these requirements and instructions.  However, these are only
required for github and Galaxy users, and not for users who
use the packaged roles, where it is confusing to see instructions
about installing requirements when none are needed.  We need to
make it easier to remove these sections when packaging.
> docs: add Collection requirements section

- tests/tests_basics_files.yml
- tests/tests_ovirt_elasticsearch.yml
- tests/tests_relp.yml
Enhancement:
Set `tests::uses_selinux` tag to the test playbook that uses the
selinux role, one of the selinux modules or commands internally.
Reason:
We are improving tox-lsr runcontainer.sh that runs CI tests using a container. (See also https://github.com/richm/tox-lsr/tree/container-improvements.) In the effort, we need a mechanism to skip a test that depends on SELinux since SELinux is disabled in a container, by default. 
Result:
This is a sample command line to run all the runnable CI tests using `runcontainer.sh` in `tox-lsr`.
```
tox -e container-ansible-core-2.15 -- --erase-old-snapshot --extra-rpm diffutils \
--extra-skip-tag "tests::uses_selinux" --parallel 4 \
--image-name centos-9 tests/tests_*.yml
```
As shown in the command line, by passing `--extra-skip-tag …
> ci: Add tests::uses_selinux tag

- defaults/main.yml
- roles/rsyslog/tasks/inputs/ovirt/set_vars.yml
- roles/rsyslog/tasks/set_vars.yml
Cause: The comparison of the present facts with the required facts is
being done on unsorted lists.
Consequence: The comparison may fail if the only difference is the
order.  Facts are gathered unnecessarily.
Fix: Use `difference` which works no matter what the order is.  Ensure
that the fact gathering subsets used are the absolute minimum required.
Result: The role gathers only the facts it requires, and does
not unnecessarily gather facts.
> fix: facts being gathered unnecessarily

- roles/rsyslog/tasks/inputs/ovirt/main.yml
The motivation was getting rid of the need to use the `ansible_selinux` fact.
The configuration of the selinux policy for the collectd port was using
a `shell`.  This has been changed to use the selinux role.
In addition - the logic would cause rsyslogd to restart every time, so that
logic has been preserved.
I don't think anyone is using the ovirt functionality, so it probably doesn't
matter, but in the future we should make the configuration of the port
conditional on `logging_manage_selinux`, possibly also configure firewall,
and make the `notify` conditional upon changes.
> refactor: Use selinux role instead of selinux cli

- README.md
format the pki parameters just like all of the other section
parameters
> docs: reformat pki params

- .github/dependabot.yml
- .github/workflows/weekly_ci.yml
Add dump_packages callback to weekly_ci so we can get
lists of packages for ostree builds.
> ci: add dump_packages to weekly_ci

- .github/dependabot.yml
This adds the dump_packages.py callback which will dump the
arguments to the `package` module (except for `state: absent`)
to the integration test run logs.  The output looks like this:
`lsrpackages: pkg-a pkg-b ...`
We will have tooling which will scrape the logs to extract the
packages used at runtime and testing for all of the supported
combinations of distribution and version.
This also ensures the weekly-ci PR git commit message conforms
to commitlint.
> ci: use dump_packages.py callback to get packages used by role

- roles/rsyslog/templates/global.j2
Enhancement: Check that `logging_max_message_size` is set, not `rsyslog_max_message_size`
Reason: The play does not check if the correct variable is defined
Result: Changed so that the test and action use the same variable name
> fix: check that logging_max_message_size is set, not rsyslog_max_message_size

- tests/tests_relp.yml
add tests for logging_max_message_size and logging_preserve_fqdn
> test: add tests for preserveFQDN, max_message_size

- .ansible-lint
- .ostree/get_ostree_data.sh
- meta/collection-requirements.yml
- roles/rsyslog/tasks/deploy.yml
- roles/rsyslog/tasks/deploy_nolog.yml
- roles/rsyslog/tasks/main_core.yml
- roles/rsyslog/tasks/set_vars.yml
- tests/tests_enabled.yml
- tests/tests_purge_reset.yml
- tests/tests_relp.yml
- tests/tests_remote.yml
- tests/tests_server.yml
The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …
> refactor: improve support for ostree systems

- roles/rsyslog/tasks/main_core.yml
Cause: The code was using `to_nice_json` to construct a list used for
further processing.
Consequence: The variable was evaluated as a `string`, not a `list`
and was causing no files to match.
Fix: Remove the `to_nice_json` so the variable is evaluated as
a `list`.
Result: The code works as expected.
> fix: ansible-core-2.16 - only use to_nice_json for output formatting

- roles/rsyslog/templates/input_basics.j2
- roles/rsyslog/templates/input_basics_rhel7.j2
Enhancement: As documented in main [rsyslog documentation](https://rsyslog.readthedocs.io/en/latest/configuration/modules/imjournal.html), `ratelimit.burst` have some sense only when `ratelimit.interval` is configured and different from zero.
Reason: Improve `ratelimit.burst`  configuration when `ratelimit.interval` is disable (equal to zero)
Result: `ratelimit.burst` is not present when `ratelimit.interval` is disable (equal to zero)
Issue Tracker Tickets (Jira or BZ if any):
> fix: avoid conf of RatelimitBurst when RatelimitInterval is zero

- tests/tests_imuxsock_files.yml
The test makes rsyslog listen to /dev/log.  We have to
restore /dev/log for journald on the systems where
journald listens for /dev/log, by restarting the journald
units.
> test: restore journald /dev/log after imuxsock test

- roles/rsyslog/templates/input_basics.j2
- Input of type imuxsock does not support the "name" parameter. When name is provided, rsyslog ouputs this error: parameter 'name' not known -- typo in config file?
- Indend if expressions for style
- Do not append input_template.j2 when use_imuxsock
See RHEL-35561
> fix: Remove name="basics_imuxsock" parameter from imuxsock type input

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-plugin-scan.yml
- .github/workflows/ansible-test.yml
- .yamllint.yml
- tests/tests_combination.yml
The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …
> ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

- .ostree/packages-runtime-RedHat-10.txt
- .ostree/packages-testing-RedHat-10.txt
- meta/main.yml
According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …
> fix: add support for EL10

- README.md
- roles/rsyslog/templates/input_files.j2
- tests/tests_files_files.yml
Feature: Add support for reopen_on_truncate for files input.  This is
a boolean value which sets the rsyslog reopenOnTruncate option for
the imfile module.
Reason: Users need to be able to configure rsyslog to reopen
input file when it was truncated.
Result: Users can configure rsyslog reopenOnTruncate.
> feat: add support for reopen_on_truncate for files input

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/files/90-custom-output.conf
- tests/tests_basics_files.yml
Feature: Allow users to provide custom logging configuration files
using the new variable `logging_custom_config_files` which is a list
of config files to copy to the default logging configuration directory.
For example, this directory for rsyslog is `/etc/rsyslog.d/`.  This
assumes the logging configuration will load all files matching `*.conf`
in this directory as in the default rsyslog directive
`$IncludeConfig /etc/rsyslog.d/*.conf`.
Reason: Users need customized configuration not provided by the role.
The role allowed this previously by the use of the variable
`rsyslog_custom_config_files`, but that variable was intended to be used
privately and is now marked DEPRECATED.
Result: Users can provide custom configuration in a supported manner.
Signed-off-by: Rich Megginson …
> feat: support custom config files with logging_custom_config_files

- README.md
- roles/rsyslog/templates/output_files.j2
- tests/tests_files_files.yml
Feature: Add support for specifying the mode, owner, and group for files
and directories created by `logging_output` type `files`.  The new variables
are `mode`, `owner`, `group`, `dir_mode`, `dir_owner`, `dir_group` and
these correspond to the Ansible `file` et. al. modules parameters.
Reason: Users must be able to set ownership/permissions for files and
directories created by rsyslog.
Result: Users are able to set ownership/permissions for files and
directories created by rsyslog.
> feat: add support for file and directory mode/owner/group for output files

- tests/tests_relp.yml
The tests_relp is causing AVCs.  Use selinux in the test to
avoid the AVCs.
> test: use selinux for relp to fix test AVC

- tests/tests_imuxsock_files.yml
Due to https://github.com/systemd/systemd/pull/33874
we need to clear the SubState=dead-resources-pinned of journald
when restarting it after the test.
> test: workaround a systemd issue in el10 restarting journald

- tests/tasks/compare_file_to_content.yml
- tests/tests_basics_forwards.yml
On some platforms the parameters are stored in a `dict`, and the ordering
of the elements is not guaranteed to be stable.  So when comparing
the expected results to the actual file, sort both.
> test: sort files to compare

- tests/tests_combination.yml
The test will fail with `ANSIBLE_GATHERING=explicit` because
the test needs facts.  Ensure `gather_facts: true` with the
test.
> test: tests_combination.yml requires fact gathering

- tests/tests_imuxsock_files.yml
Restarting journald seems to break the ability of dbus to
configure policy for newly installed services.  Restarting
dbus broker seems to fix that.
> test: restart dbus broker after restarting journald

- tests/tests_imuxsock_files.yml
Restarting journald and dbus also causes problems for systemd-logind, so
restart it too and test with loginctl
> test: restart logind and test

- defaults/main.yml
- tests/vars/rh_distros_vars.yml
We have a lot of requests to support Rocky and Alma in various system roles. The
first part of adding support is adding `vars/` files for these platforms. In
almost every case, for a given major version N, the vars file RedHat_N.yml can
be used for CentOS, Rocky, and Alma.  Rather than making a copy of the
RedHat_N.yml file, just use a symlink to reduce size and maintenance burden, and
standardize this across all system roles for consistency.
NOTE: There is no Alma or Rocky version 7 or less.
NOTE: OracleLinux is not a strict clone, so we are not going to do this for
OracleLinux at this time.  Support for OracleLinux will need to be done in
separate PRs. For more information, see
https://github.com/linux-system-roles/cockpit/issues/130
**Question**: Why not just use …
> refactor: Use vars/RedHat_N.yml symlink for CentOS, Rocky, Alma wherever possible

- .ansible-lint
- README.md
- defaults/main.yml
- roles/rsyslog/defaults/main.yml
- roles/rsyslog/tasks/main_core.yml
- roles/rsyslog/templates/custom_templates.j2
- roles/rsyslog/templates/output_files.j2
- roles/rsyslog/templates/output_forwards.j2
- roles/rsyslog/templates/output_relp.j2
- roles/rsyslog/templates/output_remote_files.j2
- roles/rsyslog/vars/outputs/files/main.yml
- roles/rsyslog/vars/outputs/forwards/main.yml
- tasks/main.yml
- tests/tests_basics_files.yml
Feature: Allow users to specify custom templates to use for `files` and
`forwards` outputs.  Users can specify a list of templates to use with
`logging_custom_templates`.  Users can specify the default template to use for
all `files` outputs with `logging_files_template_format`, or specify on a per
output basis by using `template`.  Users can specify the default template to
use for all `forwards` outputs with `logging_forwards_template_format`, or
specify on a per output basis by using `template`.
Reason: Users need the ability to format log entries in different ways other
than the built-in defaults, using custom templates.
Result: Users can specify custom templates to use for files and forwards
outputs.
> feat: support custom templates

- roles/rsyslog/vars/Debian.yml
On RedHat, it's named "iproute" but on Debian based systems it's named "iproute2"
Enhancement: Make this role functional again for Debian based systems
Reason: Newer version of this role (see commit 64f915a5c) included the package "iproute" which is named "iproute2" on Debian based systems.
Result: Define an own __rsyslog_base_packages list for Debian based systems
Issue Tracker Tickets (Jira or BZ if any):
> fix: Add a variable for rsyslog base package on Debian

- roles/rsyslog/tasks/main_core.yml
- tests/tests_imuxsock_files.yml
Cause: During the "Reset original confs" step, the role tried to remove
packages like `iproute`.
Consequence: Removal may fail because other packages require iproute,
such as as dhcp-client.
Fix: Only remove rsyslog related packages during the reset step.
Result: The role does not remove unrelated packages and works on Fedora
≥ 41 as well.
Signed-off-by: Martin Pitt <mpitt@redhat.com>
----
The test has always failed on F41 since its inception (see #358 and e. g. [this log](https://dl.fedoraproject.org/pub/alt/linuxsystemroles/logs/tf_logging-358_Fedora-41-2.17_20241207-081546/artifacts/)). This is quite a serious bug also on RHEL/CentOS.
https://issues.redhat.com/browse/RHELMISC-11204
> fix: Only remove rsyslog* packages, remove packages with command line

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-test.yml
- .github/workflows/qemu-kvm-integration-tests.yml
- meta/main.yml
- roles/rsyslog/handlers/main.yml
- roles/rsyslog/tasks/main_core.yml
- tasks/certificate.yml
- tasks/main.yml
- tasks/set_vars.yml
- tests/tasks/test_logger.yml
- tests/tests_cert_container.yml
- tests/tests_combination.yml
- tests/tests_enabled.yml
- tests/tests_imuxsock_files.yml
- tests/tests_remote.yml
- tests/tests_server.yml
Feature: Support running the cockpit role during container builds.
Reason: This is particularly useful for building bootc derivative OSes.
Result: These flags enable running the bootc container scenarios in CI, which ensures that the role works in buildah build environment. This allows us to officially support this role for image mode builds.
Do *not* enable the role for system containers (the `container`) flag. `rsyslog.service` is not designed to work in containers, and fails in all RHEL/CentOS and older Fedora releases (it finally works in Fedora 42).
Fixes https://issues.redhat.com/browse/RHEL-88689
---
> feat: Support this role in container builds

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-test.yml
- .github/workflows/qemu-kvm-integration-tests.yml
Use tox-lsr 3.12.0 for the new osbuild_config.yml feature for bootc and users
https://github.com/linux-system-roles/tox-lsr/pull/211
> ci: use tox-lsr 3.12.0 for osbuild_config.yml feature
